---
- name: cockpit
  hosts: centos
  tasks:
    - name: install cockpit
      yum:
        name: cockpit
        state: latest
    - name: ensure cockpit is enabled and running
      service:
        name: cockpit.socket
        state: running
        enabled: yes
    - name: add cockpit to firewall rules
      firewalld:
        service: cockpit
        zone: public
        state: enabled
        permanent: true
