---
# ------------------------------------------------------------------------------
- include: ../weave/enable.yml

# ------------------------------------------------------------------------------
- name: run publisher
  hosts: master
  tasks:
    - name: start publisher
      command: docker run --detach=true --net=weave --name rti-perftest-pub guther/rti-perftest -pub -sleep 1000

# ------------------------------------------------------------------------------
- name: run subscribers
  hosts: nodes
  tasks:
    - name: start subscribers
      command: docker run --detach=true --net=weave --name rti-perftest-sub guther/rti-perftest -sub
...
