---
# ------------------------------------------------------------------------------
- name: stop publisher
  hosts: master
  tasks:
    - name: stop publisher
      command: docker rm -f rti-perftest-pub

# ------------------------------------------------------------------------------
- name: stop subscribers
  hosts: nodes
  tasks:
    - name: stop subscriber
      command: docker rm -f rti-perftest-sub
...
