---
# ------------------------------------------------------------------------------
- name: docker - testing
  hosts: centos
  tasks:
    - name: docker - uninstall docker
      yum:
        name: "{{ item }}"
        state: removed
      with_items:
        - docker
        - docker-common
        - docker-selinux
        - container-selinux

    # --------------------------------------------------------------------------
    - name: docker-engine - add repository
      yum_repository:
        file: docker
        name: dockerrepo
        description: Docker Repository
        baseurl: https://yum.dockerproject.org/repo/testing/centos/7/
        gpgkey: https://yum.dockerproject.org/gpg
        gpgcheck: no
        state: present

    - name: docker-engine - install
      yum:
        name:
          - docker-engine
        state: latest
        update_cache: yes

    - name: docker-engine - enable and start
      service:
        name: docker.service
        state: running
        enabled: yes
...
