---
# ------------------------------------------------------------------------------
- include: ../base/disable-firewall.yml
- include: ../docker/deploy.yml
- include: install.yml
# ------------------------------------------------------------------------------
- name: enable master
  hosts: centos
  tasks:
    - name: launch scope
      command: scope launch
...
