---
# ------------------------------------------------------------------------------
- name: scope
  hosts: centos
  tasks:
    - name: download scope
      command: curl -L git.io/scope -o /usr/local/bin/scope creates=/usr/local/bin/scope
    - name: allow execution of scope
      file:
        path: /usr/local/bin/scope
        mode: "a+x"
...
