---
- name: docker
  hosts: centos
  tasks:
    - name: install docker
      yum:
        name: docker
        state: latest
    - name: ensure docker is enabled and running
      service:
        name: docker.service
        state: running
        enabled: yes
