---
# ------------------------------------------------------------------------------
- include: ../base/disable-firewall.yml
- include: install.yml

# ------------------------------------------------------------------------------
- name: enable master
  hosts: master
  tasks:
    - name: ensure docker is available
      command: which docker
      register: docker_command
      failed_when: docker_command.rc != 0

    - name: weave status
      command: weave status
      register: weave_status

    - name: create directory for CNI
      file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: 0775
      when: weave_status.rc != 0

    - name: create directory for CNI
      file:
        path: /etc/cni/net.d
        state: directory
        owner: root
        group: root
        mode: 0775

    - name: setup weave
      command: weave setup
      when: weave_status.rc != 0

    - name: launch weave
      command: weave launch
      when: weave_status.rc != 0

# ------------------------------------------------------------------------------
- name: enable nodes
  hosts: nodes
  tasks:
    - name: ensure docker is available
      command: which docker
      register: docker_command
      failed_when: docker_command.rc != 0

    - name: weave status
      command: weave status
      register: weave_status

    - name: create directory for CNI
      file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: 0775
      when: weave_status.rc != 0

    - name: create directory for CNI
      file:
        path: /etc/cni/net.d
        state: directory
        owner: root
        group: root
        mode: 0775
      when: weave_status.rc != 0

    - name: setup weave
      command: weave setup
      when: weave_status.rc != 0

    - name: launch weave
      command: weave launch {{ item }}
      with_items: "{{ groups['master'][0] }}"
      when: weave_status.rc != 0
...
