---
# ------------------------------------------------------------------------------
- include: ../base/disable-firewall.yml
- include: ../docker/deploy.yml
- include: install.yml
# ------------------------------------------------------------------------------
- name: enable master
  hosts: master
  tasks:
    - name: reset weave
      command: weave reset --force
    - name: launch weave
      command: weave launch
# ------------------------------------------------------------------------------
- name: enable nodes
  hosts: nodes
  tasks:
    - name: reset weave
      command: weave reset --force
    - name: launch weave
      command: weave launch {{ item }}
      with_items: "{{ groups['master'][0] }}"
...
