---
apiVersion: v1
kind: Pod
metadata:
  name: rti-perftest-pub
spec:
  containers:
    - name: rti-perftest-pub
      image: guther/rti-perftest
      args:
        - "-pub"
        - "-dataLen"
        - "1024"
        - "-sleep"
        - "1"
        - "-enableTurboMode"
        #- "-numSubscribers"
        #- "{{ groups['nodes'] | length }}"
      ports:
        - containerPort: 7400
          protocol: "udp"
          name: "rtps2-disc-m"
        - containerPort: 7401
          protocol: "udp"
          name: "rtps2-disc-u"
        - containerPort: 7410
          protocol: "udp"
          name: "rtps2-data-m"
        - containerPort: 7411
          protocol: "udp"
          name: "rtps2-data-u"
...
