---
apiVersion: v1
kind: Pod
metadata:
  name: rti-perftest-sub
spec:
  containers:
    - name: rti-perftest-sub
      image: guther/rti-perftest
      args:
        - "-sub"
      ports:
        - containerPort: 7400
          protocol: "udp"
          name: "rtps2-disc-m"
        - containerPort: 7401
          protocol: "udp"
          name: "rtps2-disc-u"
        - containerPort: 7410
          protocol: "udp"
          name: "rtps2-data-m"
        - containerPort: 7411
          protocol: "udp"
          name: "rtps2-data-u"
...
