---
# ------------------------------------------------------------------------------
- name: run publisher and subscriber
  hosts: master
  tasks:
    - name: check for namespace
      command: kubectl get namespace rti-perftest
      register: check_namespace_rti_perftest
      failed_when: check_namespace_rti_perftest.rc > 1

    - name: create namespace
      command: kubectl create namespace rti-perftest
      when: check_namespace_rti_perftest.rc == 1

    - name: create pod definitions for publishers
      template:
        src: rti-perftest-pub.yml.j2
        dest: "/tmp/rti-perftest-pub-{{ item | to_uuid }}.yml"
      with_items: "{{ groups['master'] }}"

    - name: start publishers
      command: "kubectl apply -f /tmp/rti-perftest-pub-{{ item | to_uuid }}.yml --namespace rti-perftest"
      with_items: "{{ groups['master'] }}"

    - name: delete pod definitions
      command: "rm -f /tmp/rti-perftest-pub-{{ item | to_uuid }}.yml"
      with_items: "{{ groups['master'] }}"

    - name: create pod definitions for subscribers
      template:
        src: rti-perftest-sub.yml.j2
        dest: "/tmp/rti-perftest-sub-{{ item | to_uuid }}.yml"
      with_items: "{{ groups['nodes'] }}"

    - name: start subscribers
      command: "kubectl apply -f /tmp/rti-perftest-sub-{{ item | to_uuid }}.yml --namespace rti-perftest"
      with_items: "{{ groups['nodes'] }}"

    - name: delete pod definitions
      command: "rm -f /tmp/rti-perftest-sub-{{ item | to_uuid }}.yml"
      with_items: "{{ groups['nodes'] }}"
...
