---
# ------------------------------------------------------------------------------
- name: stop publisher and subscriber
  hosts: master
  tasks:
    - name: stop publishers
      command: "kubectl delete pod rti-perftest-pub-{{ item | to_uuid }}"
      with_items: "{{ groups['master'] }}"

    - name: stop subscribers
      command: "kubectl delete pod rti-perftest-sub-{{ item | to_uuid }}.yml"
      with_items: "{{ groups['nodes'] }}"

    - name: check for namespace
      command: kubectl get namespace rti-perftest
      register: check_namespace_rti_perftest
      failed_when: check_namespace_rti_perftest.rc > 1

    - name: delete namespace
      command: kubectl delete namespace rti-perftest
      when: check_namespace_rti_perftest.rc == 0
...
